server:
  port: 8899
  servlet:
    context-path: /other
spring:
  application:
    name: order
  freemarker:
    template-loader-path: /clash/ftl/


debug: on

freemarker:
  sava-path: /usr/config/clash/
  down-url: http://domain/clash/