server:
  port: 8899
  servlet:
    context-path: /other
spring:
  application:
    name: order
  freemarker:
    cache: false
    # 模板路径
    template-loader-path: classpath:/clash/ftl/
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
  profiles:
    active: local


debug: on

