config:
  common:
    api_mode: false
    api_access_token: ""
    default_url: []
    enable_insert: ""
    insert_url: []
    prepend_insert_url: false
    exclude_remarks: []
    include_remarks: []
    filterScript: ""
    base_path: ""
    clash_rule_base: ""
    surge_rule_base: ""
    surfboard_rule_base: ""
    mellow_rule_base: ""
    quan_rule_base: ""
    quanx_rule_base: ""
    loon_rule_base: ""
    default_external_config: ""
    append_proxy_type: false
    proxy_config: ""
    proxy_ruleset: ""
    proxy_subscription: ""

  surge_external_proxy:
    surge_ssr_path: ""
    resolve_hostname: false

  node_pref:
    UDPFlag: ""
    TFOFlag: ""
    skipCertVerify: ""
    TLS13Flag: ""
    enableSort: false
    sortScript: ""
    filterDeprecated: false
    appendUserinfo: false
    clashUseNewField: false
    clashProxiesStyle: ""

  userinfo:
    stream_rule: ""
    time_rule: ""

  managed_config:
    write_managed_config: false
    managed_config_prefix: ""
    config_update_interval: 0
    config_update_strict: false
    quanx_device_id: ""

  emojis:
    add_emoji: false
    remove_old_emoji: false
    rule: ""

  rulesets:
    enabled: false
    overwrite_original_rules: false
    update_ruleset_on_request: false
    ruleset: []
    surge_ruleset: []

  proxy_groups:
    custom_proxy_group: []

  template:
    template_path: ""
    managed_config_prefix: ""

  aliases: {}

  tasks:
    task: []

  server:
    listen: ""
    port: 0
    serve_file_root: ""

  advanced:
    log_level: info
    print_debug_info: false
    max_pending_connections: 0
    max_concurrent_threads: 0
    max_allowed_rulesets: 0
    max_allowed_rules: 0
    max_allowed_download_size: 0
    enable_cache: false
    cache_subscription: 0
    cache_config: 0
    cache_ruleset: 0
    serve_cache_on_fetch_fail: false
    script_clean_context: false
    async_fetch_ruleset: false
    skip_failed_links: false